myapp/lunchmap/urls.py
from django.urls import path
from . import views

app_name = 'lunchmap'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('lunchmap/', include('lunchmap.urls')),
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url='/lunchmap/')),
]

myapp/lunchmap/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Shop(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField(blank=True)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lunchmap:detail', kwargs={'pk': self.pk})

myapp/lunchmap/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Shop

class IndexView(generic.ListView):
    model = Shop

class DetailView(generic.DetailView):
    model = Shop

class CreateView(generic.edit.CreateView):
    model = Shop
    fields = '__all__'

class UpdateView(generic.edit.UpdateView):
    model = Shop
    fields = '__all__'

class DeleteView(generic.edit.DeleteView):
    model = Shop
    success_url = reverse_lazy('lunchmap:index')

myapp/lunchmap/templates/lunchmap/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'></link>;
        <style>body {padding-top: 80px;}</style>
        <title>Lunchmap</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Lunchmap</a>
        </nav>
        
        <div class='container'>
            
            {% block content %}
           
            {% endblock %}
        </div>
    </body>
</html>

myapp/lunchmap/templates/lunchmap/shop_confirm_delete.html
{% extends './base.html' %}
{% block content %}

<h1>お店情報の削除</h1>
<p>'{{ object.name }}'を削除しますか?</p>
<form action='' method='post'>{% csrf_token %}
    <button type='submit' class='submit delete'>削除する</button>
</form>

<div>
    <p><a href='JavaScript:history.back()'>&lt; 戻る</a></p>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_detail.html
{% extends './base.html' %}
{% block content %}

<h1>{{ shop.name }}</h1>
<div>
    <p>{{ shop.category.name }}</p>
    <p>{{ shop.address }}</p>
</div>
<iframe id='map'
    src='https://www.google.com/maps/embed/v1/place?key=AIzaSyB7EhG6EMzlC6HR5MBo3yke61pkEPtNSxA
    &q={{ shop.address }}'
    width='100%'
    height='320'
    frameborder='0'>
</iframe>
<div>
    <a href='{% url "lunchmap:index" %}'>一覧</a> |
    <a href='{% url "lunchmap:update" shop.pk %}'>編輯</a> |
    <a href='{% url "lunchmap:delete" shop.pk %}'>刪除</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_form.html
{% extends './base.html' %}
{% block content %}

<h1>店家的情報{{ object|yesno:'更新,製作'}}</h1>

<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-outline-info'>{{ object|yesno:'更新,製作'}}</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 返回</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_list.html
{% extends './base.html' %}
{% block content %}

        
<h1>店家一覽</h1>


<table class='table table-active table-hover'>
    <tr>
        <th>類別</th><th>店名</th><th>地址</th>
    </tr>
    {% for shop in object_list %}
    <tr>
        <td>{{ shop.category.name }}</td>
        <td><a href='{% url "lunchmap:detail" shop.pk %}'>{{ shop.name }}</a></td>
        <td>{{ shop.address }}</td>
    </tr>
    {% endfor %}
</table>

<div>
    <a href='{% url "lunchmap:create" %}'>新店家</a>
</div>
{% endblock %}